// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggHPfLr4aVIQWaghIj8GZR3T7Sa2VWE4',
    appId: '1:367062705541:web:5f779cfd7a526a377fd0ec',
    messagingSenderId: '367062705541',
    projectId: 'flutterexpensetracker-692f6',
    authDomain: 'flutterexpensetracker-692f6.firebaseapp.com',
    storageBucket: 'flutterexpensetracker-692f6.appspot.com',
    measurementId: 'G-LS8LXZEE95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI5g3gvSnJrvcE7SrzK4oD7haQPVoWb9c',
    appId: '1:367062705541:android:09c38f74aef46a1b7fd0ec',
    messagingSenderId: '367062705541',
    projectId: 'flutterexpensetracker-692f6',
    storageBucket: 'flutterexpensetracker-692f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-wGDqXZ_bUZ4sHZbOdTPA6w3oOHEU2c',
    appId: '1:367062705541:ios:b58b1bb9e30cc2897fd0ec',
    messagingSenderId: '367062705541',
    projectId: 'flutterexpensetracker-692f6',
    storageBucket: 'flutterexpensetracker-692f6.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-wGDqXZ_bUZ4sHZbOdTPA6w3oOHEU2c',
    appId: '1:367062705541:ios:b58b1bb9e30cc2897fd0ec',
    messagingSenderId: '367062705541',
    projectId: 'flutterexpensetracker-692f6',
    storageBucket: 'flutterexpensetracker-692f6.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAggHPfLr4aVIQWaghIj8GZR3T7Sa2VWE4',
    appId: '1:367062705541:web:56007232a37a2e847fd0ec',
    messagingSenderId: '367062705541',
    projectId: 'flutterexpensetracker-692f6',
    authDomain: 'flutterexpensetracker-692f6.firebaseapp.com',
    storageBucket: 'flutterexpensetracker-692f6.appspot.com',
    measurementId: 'G-3B85PCQW0H',
  );
}
